### ISSUE TITLE
Email requirement

### ISSUE THREAD

**Issue by srirachapills** [klaviyo/ruby-klaviyo#15]
According to [documentation](https://www.klaviyo.com/docs) for the track and identify APIs, email or phone_number key can be supplied:
> Custom information about the person who did this event. You must identify the person by their email using a $email key (or by their phone number using a $phone_number key if you have SMS-only contacts). Other than that, you can include any data you want and it can then be used to create segments of people. For example, if you wanted to create a list of people on trial plans, include a person's plan type in this hash so you can use that information later.

Should the email or id check be changed accordingly?
I am working on a product where customers can sign up with a phone number only, optionally setting their email...

https://github.com/klaviyo/ruby-klaviyo/blob/c3f11a52131e5bbe225d20d620021386a0f4ebac/lib/klaviyo/client.rb#L66

**Comment by remstone7** [comment]
Hey @srirachapills , yes you're correct that if $phone_number is applied we should accept it.  This will need to get patched

**Comment by srirachapills** [comment]
If we can release [that](https://github.com/klaviyo/ruby-klaviyo/pull/17) soon it would be awesome 😛

**Comment by cpcurtis1218** [comment]
> If we can release [that](https://github.com/klaviyo/ruby-klaviyo/pull/17) soon it would be awesome 😛

I've released the update to add the phone numbers to the public API and added an example to the README.  The $phone_numbers was just an update to the code and you can now use the 'phone_number' argument to add SMS profiles.

**Comment by srirachapills** [comment]
@cpcurtis1218 the identify API is now accepting phone only.
However, the track API, which is the example you added to the README, is not working as expected. It is accepted by the API (returns a `1`) but the event is never showing up in the Klaviyo dashboard. Thus, I'm wondering if that is supported or a Klaviyo bug.

**Comment by cpcurtis1218** [comment]
Hey @srirachapills could you send over the request that you're using, and also confirm that your Public API key is correct?  My tests have been successful in using both the Track and Identify APIS for both email and phone_number events using the current version of the SDK.

**Comment by srirachapills** [comment]
Here's what I do:

```
➜ bundle info klaviyo
  * klaviyo (2.0.2)
        Summary: You heard us, a Ruby wrapper for the Klaviyo API
        Homepage: https://www.klaviyo.com/
        Path: /Users/jmelanson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/klaviyo-2.0.2
➜ rails c
irb(main):003:0> Klaviyo::Public.track('Rails First Event', phone_number: '+10000000000', properties: {first_name: 'Ruby', last_name: 'Test', zipcode: '90401'})
  HTTP GET (43.46ms)   https://a.klaviyo.com:443/api/track?data=eyJ0b2tlbiI6IlFYemlYbiIsImV2ZW50IjoiUmFpbHMgRmlyc3QgRXZlbnQiLCJwcm9wZXJ0aWVzIjp7ImZpcnN0X25hbWUiOiJSdWJ5IiwibGFzdF9uYW1lIjoiVGVzdCIsInppcGNvZGUiOiI5MDQwMSJ9LCJjdXN0b21lcl9wcm9wZXJ0aWVzIjp7IiRwaG9uZV9udW1iZXIiOiIrMTAwMDAwMDAwMDAifX0=
  Response status   Net::HTTPOK (200)
  Response body   1
=> "1"
```

Public Key is correct since I am able to do the exact same operation with an email address instead of phone number only.

Looking at Metrics in dashboard, I don't see that event, but I can see the email-only one.

**Comment by cpcurtis1218** [comment]
@srirachapills Thanks for sending that over! The reason that this isn't actually saving to Klaviyo is that we do validate phone numbers before saving events.  The '1' from the API indicates that the format of the request is correct, but later down the line, Klaviyo is checking the phone number '+10000000000' and since this isn't a valid phone number, the events won't save.  Using a real phone number should resolve the issue.

**Comment by srirachapills** [comment]
Forgot to mention, this is using a valid phone number (Canadian), 0s are just masking the real one.

**Comment by cpcurtis1218** [comment]
@srirachapills Understood, thank you for confirming.  I tested the request that you sent over and updated the phone number with my own and the 'Rails First Event' successfully appeared in my test Klaviyo account.  I believe that the issue that you're seeing is that either you don't have SMS set up in your Klaviyo account (https://help.klaviyo.com/hc/en-us/articles/360035525311-Getting-Started-with-SMS-and-MMS#checklist1) or, the number isn't being accepted since it's a Canadian phone number.  At this time, Klaviyo is only setup to support US phone numbers, however, I was under the impression that we would still accept international numbers, just not send SMS message to them.  Would you be able to try a US phone number as a test?

**Comment by srirachapills** [comment]
Enabling SMS solved it. Thanks for you help!

**Comment by cpcurtis1218** [comment]
Great, thanks for letting me know!
