### ISSUE TITLE
Adding `trackViewedItem` to Public Api

### ISSUE THREAD

**Issue by SeanArmstrong** [klaviyo/ruby-klaviyo#20]
Looking at documentation for the client side I believe there is some missing functionality from the Klaviyo::Public api

This below link talks about Recently Viewed Items using a custom `trackViewedItem` event similar to that of identify
https://help.klaviyo.com/hc/en-us/articles/360019921772-How-to-Insert-Recently-Viewed-Items-into-an-Email

Is there any plans to add this or can this be achieved by using Klaviyo::Public.track method?

Thanks!

**Comment by smoucka** [comment]
Hi @SeanArmstrong 

Great question, the trackViewedItem method is specific to [Klaviyo's Javascript API](https://www.klaviyo.com/docs/getting-started) (although it's not documented). It's built upon the identify endpoint so this data is saved as a profile property rather than events. All this method does is save an array of hashes containing Viewed Product data to the browsers local storage. In addition to the Viewed Product properties each hash in the array contains a count for how many times that product has been viewed and a timestamp for the most recent view. This array is limited to the previous 30 days. Each time this method is called the array is updated and then sent to Klaviyo and overwrites the existing property on that profile. 

You could certainly re-create it's functionality using Klaviyo::Public.identify.

I'm going to mark this issue as closed but don't hesitate to follow up if you have any other questions.

**Comment by SeanArmstrong** [comment]
Thanks for the fast response @smoucka . That all makes sense.

Cheers!
