### ISSUE TITLE
check_list_subscriptions uses the incorrect endpoint

### ISSUE THREAD

**Issue by PaulMorel1** [klaviyo/ruby-klaviyo#39]
There appears to be a bug in this ruby gem on the check_list_subscriptions method. This method is supposed to check if a user is on a list AND they aren't unsubscribed.

See documentation here: https://apidocs.klaviyo.com/reference/lists-segments#get-list-subscriptions

That indicates that this method should hit `https://a.klaviyo.com/api/v2/list/LIST_ID/get-list-subscriptions`

But in the sourcecode here: https://github.com/klaviyo/ruby-klaviyo/blob/master/lib/klaviyo/apis/lists.rb

you can see that it is hitting `"#{LIST}/#{list_id}/#{SUBSCRIBE}"` and `SUBSCRIBE` is set to `'subscribe'`.

GET on that endpoint is not described in the documentation, but it appears to check list membership without checking against unsubscribes.

The fix is to correct that URL to be `"#{LIST}/#{list_id}/get-list-subscriptions"`, although you will want to use a constant to follow the existing pattern.

**Comment by cpcurtis1218** [comment]
Thank you for bringing attention to this!  You are correct that the documentation describes a POST request for the `/get-list-subscriptions` endpoint. the SDK currently uses an older version of the APIs and I've confirmed that the GET request does currently work to the `/subscribe` endpoint.  That being said, I am updating this in order to make it a POST request with the updated endpoint in order to match the updated documentation.  This updated will be released soon.  Closing this issue.
